### ISSUE TITLE
hello sir, i am getting these issues

### ISSUE THREAD

**Issue by AniketDeshmane** [FutureSharks/rpi-security#55]
Traceback (most recent call last):
  File "/usr/local/bin/rpi-security.py", line 9, in <module>
    import rpisec
  File "/usr/local/lib/python3.7/dist-packages/rpisec/__init__.py", line 4, in <module>
    from .rpis_camera import RpisCamera
  File "/usr/local/lib/python3.7/dist-packages/rpisec/rpis_camera.py", line 7, in <module>
    import imutils
  File "/usr/local/lib/python3.7/dist-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/usr/local/lib/python3.7/dist-packages/imutils/convenience.py", line 65, in <module>
    def resize(image, width=None, height=None, inter=cv2.INTER_AREA):
AttributeError: module 'cv2' has no attribute 'INTER_AREA'

**Comment by FutureSharks** [comment]
What version of OpenCV do you have? did you follow [the instructions](https://github.com/FutureSharks/rpi-security#installation-configuration-and-running)?

**Comment by AniketDeshmane** [comment]
i am followed the steps , but getting this error

**Comment by FutureSharks** [comment]
What version of OpenCV do you have?

**Comment by AniketDeshmane** [comment]
*Here is my config*
pi@raspberrypi:~ $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.0'


Sorry for the late reply!

**Comment by AniketDeshmane** [comment]
Should i do?

**Comment by AniketDeshmane** [comment]
Thanks for the help, turns out that Raspbian Buster OS was the problem!
Problem has solved thanks for the quick reply!
And have a great day!

**Comment by FutureSharks** [comment]
OK! Glad you got it sorted.
